# Generated by Django 5.2 on 2025-05-01 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.CharField(max_length=100, unique=True)),
                ('host', models.CharField(max_length=100)),
                ('guest_count', models.IntegerField(default=0)),
                ('max_guests', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
